service:
  name: sls-like # deployment name

plugins:
  - serverless-bundle # webpack과 연동해서 쓰려면 필요
  - serverless-pseudo-parameters # aws 객체들을 쉽게 가져다 쓸 수 있도록

provider: # cloud 정보
  name: aws
  runtime: nodejs12.x # lamda function 언어
  memorySize: 256
  stage: ${opt:stage, 'dev'} # serverless.yml 파일에서 사용할 수 있는 변수형태. default 값 설정가능. opt 은 option
  region: ap-northeast-2 # 서비스 배포할 리전 설정. multiple region 설정도 가능

resources:
  Resources:
    LikesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LikesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions: # deploy 할 function 목록
  hello: # function 명
    handler: src/handlers/hello.handler # function 파일 : 실행할 코드 / {FILE_PATH}.{export valiable name}
    events: # 트리거 사용을 위해 events 필요
      - http:
          method: GET
          path: /hello
  createLike:
    handler: src/handlers/createLike.handler
    events:
      - http:
          method: POST
          path: /likes

custom: # 현재 서비스 전용 변수 설정
  bundle:
    linting: false # serverless-bundle plugins do not linting check