service:
  name: sls-like # deployment name

plugins:
  - serverless-bundle # webpack과 연동해서 쓰려면 필요
  - serverless-pseudo-parameters # aws 객체들을 쉽게 가져다 쓸 수 있도록

provider: # cloud 정보
  name: aws
  runtime: nodejs12.x # lamda function 언어
  memorySize: 256
  stage: ${opt:stage, 'dev'} # serverless.yml 파일에서 사용할 수 있는 변수형태. default 값 설정가능. opt 은 option
  region: ap-northeast-2 # 서비스 배포할 리전 설정. multiple region 설정도 가능
  environment:
    LIKES_TABLE_NAME: ${self:custom.LikesTable.name}
  iamRoleStatements:
    - ${file(iam/LikesTableIAM.yml):LikesTableIAM}

resources:
  Resources:
    LikesTable: ${file(resources/LikesTable.yml):LikesTable}
    BoardTable: ${file(resources/BoardTable.yml):BoardTable}

functions:
  createLike:
    handler: src/handlers/createLike.handler
    events:
      - http:
          method: POST
          path: /likes

  getLikes:
    handler: src/handlers/getLikes.handler
    events:
      - http:
          method: GET
          path: /likes

custom: # 현재 서비스 전용 변수 설정
  LikesTable:
    name: !Ref LikesTable # javascript 파일에서 필요
    arn: !GetAtt LikesTable.Arn # Resources 를 이용하는 iam 설정 파일에서 필요
  bundle:
    linting: false # serverless-bundle plugins do not linting check